### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wlh1950** [AlexSheer/phpbb3.2-Knowledge-Base#35]
I get this error when I enable the extension:

General Error
SQL ERROR [ mysqli ]

Table 'panhead.phpbb_kb_categories' doesn't exist [1146]

SQL

SELECT category_id FROM phpbb_kb_categories

BACKTRACE

**Comment by nou-nou** [comment]
Same here. Local test server. I also cannot delete data after getting that error (maybe the two are related):

phpBB 3.3.5
PHP 7.4.12
MySQL(i) 10.4.16-MariaDB

Fatal error: Uncaught TypeError: Argument 1 passed to phpbb\db\migrator::get_callable_from_step() must be of the type array, null given, called in C:\xampp\htdocs\phpbb\db\migrator.php on line 705 and defined in C:\xampp\htdocs\phpbb\db\migrator.php:727 Stack trace: #0 C:\xampp\htdocs\phpbb\db\migrator.php(705): phpbb\db\migrator->get_callable_from_step(NULL, NULL, false) #1 C:\xampp\htdocs\phpbb\db\migrator.php(662): phpbb\db\migrator->run_step(NULL, NULL, false) #2 C:\xampp\htdocs\phpbb\db\migrator.php(590): phpbb\db\migrator->process_data_step(Array, Array) #3 C:\xampp\htdocs\phpbb\db\migrator.php(518): phpbb\db\migrator->try_revert('\\sheer\\knowledg...') #4 C:\xampp\htdocs\phpbb\db\migrator.php(513): phpbb\db\migrator->revert_do('\\sheer\\knowledg...') #5 C:\xampp\htdocs\phpbb\db\migrator.php(513): phpbb\db\migrator->revert_do('\\sheer\\knowledg...') #6 C:\xampp\htdocs\phpbb\db\migrator.php(489): phpbb\db\migrator->reve in C:\xampp\htdocs\phpbb\db\migrator.php on line 727
